// BLE Nordic UART Service — advertising, connection lifecycle, RX/TX glue.
//
// Single-central design: the peripheral advertises "Pico-Terminal", waits
// for a connection, delivers a short banner over TX notifications, and
// then forwards RX writes into the CLI. Advertising restarts automatically
// on disconnect.
#include "ble/ble_nus.h"
#include "system/log.h"

#include "btstack.h"
#include "pico/cyw43_arch.h"
#include "pico/btstack_cyw43.h"

#include "nus.h"  // generated from src/ble/nus.gatt by CMake

#include <string.h>

// ---- constants --------------------------------------------------------------

// Attribute-handle names generated by compile_gatt.py from the UUIDs. The
// suffix "_01" is the instance number; there's only one NUS in the DB.
#define ATT_NUS_RX_VALUE_HANDLE \
    ATT_CHARACTERISTIC_6E400002_B5A3_F393_E0A9_E50E24DCCA9E_01_VALUE_HANDLE
#define ATT_NUS_TX_VALUE_HANDLE \
    ATT_CHARACTERISTIC_6E400003_B5A3_F393_E0A9_E50E24DCCA9E_01_VALUE_HANDLE
#define ATT_NUS_TX_CCCD_HANDLE \
    ATT_CHARACTERISTIC_6E400003_B5A3_F393_E0A9_E50E24DCCA9E_01_CLIENT_CONFIGURATION_HANDLE

// TX ring — sized to hold a few command responses without blocking. The
// shell never sends binary blobs so 1 KB is plenty; overflow drops bytes
// (best-effort transport).
#define TX_BUF_SIZE 1024

// ---- state ------------------------------------------------------------------

static bool g_initialized = false;

static hci_con_handle_t g_con_handle = HCI_CON_HANDLE_INVALID;
static bool             g_notifications_enabled = false;

static uint8_t g_tx_buf[TX_BUF_SIZE];
static size_t  g_tx_len = 0;

static ble_nus_rx_cb_t    g_rx_cb    = NULL;   static void *g_rx_user    = NULL;
static ble_nus_state_cb_t g_conn_cb  = NULL;   static void *g_conn_user  = NULL;
static ble_nus_state_cb_t g_disc_cb  = NULL;   static void *g_disc_user  = NULL;

static btstack_packet_callback_registration_t g_hci_event_reg;

// Complete Local Name = "Pico-Terminal" (13 bytes) plus flags.
// AD structure length byte counts the type byte + payload bytes.
static const uint8_t g_adv_data[] = {
    // Flags: LE General Discoverable, BR/EDR not supported
    0x02, BLUETOOTH_DATA_TYPE_FLAGS, 0x06,
    // Complete Local Name
    0x0E, BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME,
    'P', 'i', 'c', 'o', '-', 'T', 'e', 'r', 'm', 'i', 'n', 'a', 'l',
};

// Scan response advertises the 128-bit NUS service UUID (little-endian).
// UUID string 6E400001-B5A3-F393-E0A9-E50E24DCCA9E reversed to LE:
//   9E CA DC 24 0E E5 A9 E0 93 F3 A3 B5 01 00 40 6E
static const uint8_t g_scan_resp[] = {
    0x11, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_128BIT_SERVICE_CLASS_UUIDS,
    0x9E, 0xCA, 0xDC, 0x24, 0x0E, 0xE5, 0xA9, 0xE0,
    0x93, 0xF3, 0xA3, 0xB5, 0x01, 0x00, 0x40, 0x6E,
};

// ---- TX ring ----------------------------------------------------------------

static size_t tx_enqueue(const uint8_t *data, size_t len) {
    size_t space = TX_BUF_SIZE - g_tx_len;
    if (len > space) len = space;
    memcpy(g_tx_buf + g_tx_len, data, len);
    g_tx_len += len;
    return len;
}

// Pull `n` bytes off the front. memmove is fine here — the buffer is
// only 1 KB and this path is not on any hot loop.
static void tx_dequeue(size_t n) {
    if (n >= g_tx_len) {
        g_tx_len = 0;
        return;
    }
    memmove(g_tx_buf, g_tx_buf + n, g_tx_len - n);
    g_tx_len -= n;
}

static void tx_reset(void) {
    g_tx_len = 0;
}

// ---- transmit ---------------------------------------------------------------

static void request_tx_flush(void) {
    if (g_con_handle == HCI_CON_HANDLE_INVALID) return;
    if (!g_notifications_enabled) return;
    if (g_tx_len == 0) return;
    att_server_request_can_send_now_event(g_con_handle);
}

// Called on ATT_EVENT_CAN_SEND_NOW — one chunk goes out per event.
static void tx_flush(void) {
    if (g_con_handle == HCI_CON_HANDLE_INVALID) return;
    if (!g_notifications_enabled || g_tx_len == 0) return;

    uint16_t mtu = att_server_get_mtu(g_con_handle);
    if (mtu < 4) return;    // 3-byte notify header + at least 1 byte data
    size_t max_payload = (size_t)mtu - 3u;
    size_t chunk = g_tx_len < max_payload ? g_tx_len : max_payload;

    int err = att_server_notify(g_con_handle, ATT_NUS_TX_VALUE_HANDLE,
                                g_tx_buf, (uint16_t)chunk);
    if (err == ERROR_CODE_SUCCESS) {
        tx_dequeue(chunk);
    }
    // If notify failed we simply try again next can-send-now; the buffer
    // still holds the data.
    if (g_tx_len > 0) {
        att_server_request_can_send_now_event(g_con_handle);
    }
}

size_t ble_nus_send(const uint8_t *data, size_t len) {
    if (!data || len == 0) return 0;
    size_t accepted = tx_enqueue(data, len);
    request_tx_flush();
    return accepted;
}

int ble_nus_cli_write(const char *data, size_t len, void *user) {
    (void)user;
    ble_nus_send((const uint8_t *)data, len);
    return 0;
}

bool ble_nus_is_connected(void) {
    return g_con_handle != HCI_CON_HANDLE_INVALID && g_notifications_enabled;
}

// ---- callback registration --------------------------------------------------

void ble_nus_set_rx_callback(ble_nus_rx_cb_t cb, void *user) {
    g_rx_cb = cb; g_rx_user = user;
}
void ble_nus_set_connect_callback(ble_nus_state_cb_t cb, void *user) {
    g_conn_cb = cb; g_conn_user = user;
}
void ble_nus_set_disconnect_callback(ble_nus_state_cb_t cb, void *user) {
    g_disc_cb = cb; g_disc_user = user;
}

// ---- ATT read / write callbacks --------------------------------------------

// The NUS characteristics are notify-only and write-only respectively;
// there is nothing readable, so this callback stays empty.
static uint16_t att_read_callback(hci_con_handle_t handle, uint16_t att_handle,
                                  uint16_t offset, uint8_t *buffer,
                                  uint16_t buffer_size) {
    (void)handle; (void)att_handle; (void)offset;
    (void)buffer; (void)buffer_size;
    return 0;
}

static int att_write_callback(hci_con_handle_t handle, uint16_t att_handle,
                              uint16_t transaction_mode, uint16_t offset,
                              uint8_t *buffer, uint16_t buffer_size) {
    (void)transaction_mode; (void)offset;

    if (att_handle == ATT_NUS_TX_CCCD_HANDLE) {
        // Client subscribed to (or unsubscribed from) TX notifications.
        uint16_t cccd = little_endian_read_16(buffer, 0);
        bool was_enabled = g_notifications_enabled;
        g_notifications_enabled =
            (cccd & GATT_CLIENT_CHARACTERISTICS_CONFIGURATION_NOTIFICATION) != 0;

        if (g_notifications_enabled && !was_enabled) {
            g_con_handle = handle;
            LOGI("ble: notifications enabled by peer");
            if (g_conn_cb) g_conn_cb(g_conn_user);
            request_tx_flush();
        } else if (!g_notifications_enabled && was_enabled) {
            LOGI("ble: peer disabled notifications");
        }
        return 0;
    }

    if (att_handle == ATT_NUS_RX_VALUE_HANDLE) {
        if (buffer_size > 0 && g_rx_cb) {
            g_rx_cb(buffer, buffer_size, g_rx_user);
        }
        return 0;
    }

    return 0;
}

// ---- advertising helpers ----------------------------------------------------

static void start_advertising(void) {
    // 30 * 0.625 ms = 18.75 ms interval, moderate power. Public address,
    // undirected connectable, all channels.
    static const uint16_t adv_interval_min = 0x0030;
    static const uint16_t adv_interval_max = 0x0060;
    static const uint8_t  adv_type         = 0x00; // ADV_IND
    bd_addr_t null_addr = {0};

    gap_advertisements_set_params(adv_interval_min, adv_interval_max,
                                  adv_type, 0, null_addr, 0x07, 0x00);
    gap_advertisements_set_data(sizeof(g_adv_data), (uint8_t *)g_adv_data);
    gap_scan_response_set_data(sizeof(g_scan_resp), (uint8_t *)g_scan_resp);
    gap_advertisements_enable(1);
    LOGI("ble: advertising as \"Pico-Terminal\"");
}

// ---- packet handler ---------------------------------------------------------

static void packet_handler(uint8_t packet_type, uint16_t channel,
                           uint8_t *packet, uint16_t size) {
    (void)channel; (void)size;
    if (packet_type != HCI_EVENT_PACKET) return;

    switch (hci_event_packet_get_type(packet)) {
        case BTSTACK_EVENT_STATE:
            if (btstack_event_state_get_state(packet) == HCI_STATE_WORKING) {
                start_advertising();
            }
            break;

        case HCI_EVENT_META_GAP:
            // Pico-SDK's BTStack raises LE connection-complete through
            // HCI_EVENT_META_GAP / GAP_SUBEVENT_LE_CONNECTION_COMPLETE.
            // On older BTStack revisions this was HCI_EVENT_LE_META /
            // HCI_SUBEVENT_LE_CONNECTION_COMPLETE — if a build errors on
            // the constant names below, that's the migration to make.
            if (hci_event_gap_meta_get_subevent_code(packet) ==
                GAP_SUBEVENT_LE_CONNECTION_COMPLETE) {
                g_con_handle = gap_subevent_le_connection_complete_get_connection_handle(packet);
                g_notifications_enabled = false;
                tx_reset();
                LOGI("ble: connection %u", (unsigned)g_con_handle);
                // Greeting waits until the peer subscribes — we don't want
                // to fire notifications the peer has explicitly turned off.
            }
            break;

        case HCI_EVENT_DISCONNECTION_COMPLETE:
            LOGI("ble: disconnect");
            g_con_handle = HCI_CON_HANDLE_INVALID;
            g_notifications_enabled = false;
            tx_reset();
            if (g_disc_cb) g_disc_cb(g_disc_user);
            // Re-arm advertising so a new peer can connect.
            gap_advertisements_enable(1);
            break;

        case ATT_EVENT_CAN_SEND_NOW:
            tx_flush();
            break;

        default:
            break;
    }
}

// ---- init -------------------------------------------------------------------

int ble_nus_init(void) {
    if (g_initialized) return 0;

    if (cyw43_arch_init()) {
        LOGE("ble: cyw43_arch_init failed");
        return -1;
    }

    l2cap_init();
    sm_init();   // pairing/bonding not required for NUS but the SM has
                 // to be alive for BTStack's ATT server to run.

    att_server_init(profile_data, att_read_callback, att_write_callback);
    att_server_register_packet_handler(packet_handler);

    g_hci_event_reg.callback = &packet_handler;
    hci_add_event_handler(&g_hci_event_reg);

    hci_power_control(HCI_POWER_ON);
    g_initialized = true;
    return 0;
}
